# Generated by Django 4.0.4 on 2022-04-26 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_task_uname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='uname',
        ),
    ]
